---
- name: add necessary extra repositories ({{ extra_repositories|join(' - ') }})
  apt_repository: repo={{ item }} state=present update_cache=no
  with_items: "{{ extra_repositories }}"
  when: extra_repositories is defined

- name: add necessary extra repositories keys ({{ extra_repositories_keys|join(' - ') }})
  apt_key: url={{ item }} state=present
  with_items: "{{ extra_repositories_keys }}"
  when: extra_repositories_keys is defined

- name: upgrade packages
  apt: upgrade=yes update_cache=yes

- name: install necessary extra packages ({{ extra_packages|join(', ') }})
  apt: name={{ extra_packages }} state=present update_cache=yes cache_valid_time=3600 force=yes
  when: extra_packages is defined

# TODO: make configurable
# doesn't work, see issue <https://github.com/ansible/ansible-modules-extras/issues/13>
# manually edit /etc/locale.gen
#  # locale-gen
- name: set italian locale
  locale_gen: name=it_IT.UTF-8 state=present
